Develop
dai-ch/T-back-js4 pull request #1
Opened 2021-01-08 11:33 UTC by dai-ch

2021-01-09 12:36 UTC, myzktkyk requested changes
動作は問題ありませんでした。
コードについて、何点か指摘があります 🙏

2021-01-09 12:36 UTC, myzktkyk commented on main.js
> +}
- `await` を使って書く方がイマドキの書き方ですし、他言語との差異も少ないのでおススメです
- `chach` がおそらく Typo かなと思うのですが…ややわかりにくい命名だったので、名前を考え直してほしいです
  - コードの例は私の提案を書いたまでなので、無理に採用いただかなくてもいいです
- 変数 `text` を利用していないようだったので、消した方がよいかと思いました

```suggestion
const fetchQuizData = async () => {
  try {
    const response = await fetch(Api);
    const json = await response.json();
    Quiz(json);
  } catch (e) {
    console.error(e);
  }
}
```

2021-01-09 12:36 UTC, myzktkyk commented on main.js
> +btn.addEventListener('click', function () {
全体的に言えるのですが、アロー関数を用いた方が最近の書き方です。

```suggestion
btn.addEventListener('click', () => {
```

2021-01-09 12:36 UTC, myzktkyk commented on main.js
> +const funish = function () {
`finish` の Typo かなぁと推測はしますが、もしそうだとしてもちょっとわかりにくい名前です。
（ **何が** 終わったのかよくわからない）
私なら `showResult` とかにします。

2021-01-09 13:21 UTC, dai-ch commented on main.js
> +const funish = function () {
ありがとうございます。確かにfinishだとわかりずらいですね。直しました。

2021-01-09 13:21 UTC, dai-ch commented on main.js
> +btn.addEventListener('click', function () {
ありがとうございます。今後はアロー関数で書きます。

2021-01-09 14:35 UTC, dai-ch commented on main.js
> +}
ありがとうございます。
awaitを取り入れました。asyncとセットの認識で使う形でよろしかったでしょうか？
ざっくりですが、これらの2つに関して下記のような理解で使っています。
async：非同期関数を定義する、アロー関数は利用できない 
await:指定した関数の結果が返されるまで全体の処理を待機する

また、上記に関しては下記の記事を参考にしました。
https://rightcode.co.jp/blog/information-technology/javascript-async-await

2021-01-11 04:28 UTC, kouki-iwahara commented on main.js
> +}
>async：非同期関数を定義する、アロー関数は利用できない
await:指定した関数の結果が返されるまで全体の処理を待機する

両方とも一部認識間違っております。
asyncは非同期関数を定義する時に付けますが、アロー関数でも定義できます。
上記にmiyazakiさんが記載してくれているコードはアロー関数で定義されておりますね。

awaitは同期的に記述できる書き方なのですが、「全体の処理を待機する」という認識が間違っていて、awaitの理解というよりも非同期処理の理解に誤りがあります。
非同期処理とは、
「関数が呼び出されたとき、戻り値として本来渡したい結果を返すのではなく、一度関数としては終了し（＝呼び出し元に戻る）、後で『本来渡したかった値』を返せる状態になったときに、呼び出し元にその値を通知する」という仕組みです。
なので、全体の処理が止まる訳ではありません。

こちらの記事が良くまとまっていて、コメントに一部抜粋させていただきました。
https://qiita.com/kiyodori/items/da434d169755cbb20447

まだnode.jsに関することは分からないかもしれませんが、ざっと目を通しておくだけでも理解が深まるかと思います。

>chachに関してはMDNみたらエラーを取得する際に使う仕様のようなのでそのままにしました。

これに関してはご指摘内容に少し誤解をなさっていて、miyazakiさんがご指摘したのは、chachApiという命名かと思います。
chachではなくcatchのtypoではないか、というご指摘ですね。
エラーハンドリングでcatchを使用するのは正しいです。

2021-01-11 05:55 UTC, dai-ch commented on main.js
> +}
レビューありがとうございます。
  記事も拝見させて頂きました。概要はおおよそ理解できましたが、まだ使いこなえるレベルに至っていない感じがするのでVueの学習と並行してJavaScriptの非同期処理や他の弱そうな部分のキャッチアップも継続したいと思います！
  ！

2021-01-11 05:59 UTC, merged